Validate that a user_id and organization_id are passed to getClientAuthToken
Although a TS error, if you aren't using TS (or suppress the error), and
you don't pass a user_id and organization_id, you'll actually get back a
server auth token which is almost certainly not what you wanted.

Test Plan:
```
$ node
Welcome to Node.js v16.19.1.
Type ".help" for more information.
> const csdk = await import('./packages/server/dist/cjs/index.js')
undefined
> csdk.getClientAuthToken('some app id', 'some app secret', {user_id: 42, organization_id: 99})
'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0Miwib3JnYW5pemF0aW9uX2lkIjo5OSwiYXBwX2lkIjoic29tZSBhcHAgaWQiLCJpYXQiOjE2ODQ5MjI1MTIsImV4cCI6MTY4NDkyMjU3Mn0.gG2fp9VOJpybkdb75TdyQuJrTomfbynMu-fJjWpH6_dnj8tF4nn80B8YOgOqoAhIA85FIB4F7hl2TKJoMVPfBg'
> csdk.getClientAuthToken('some app id', 'some app secret', {})
Uncaught:
Error: Missing user_id or organization_id. A token without a user_id and organization_id is an administrative server auth token (which should never be given to clients). If you intended to generate a server auth token, call getServerAuthToken instead.
    at Module.getClientAuthToken (/Users/jwatzman/monorepo/opensource/sdk-js/packages/server/dist/cjs/index.js:31:15)
> csdk.getClientAuthToken('some app id', 'some app secret')
Uncaught:
Error: Missing user_id or organization_id. A token without a user_id and organization_id is an administrative server auth token (which should never be given to clients). If you intended to generate a server auth token, call getServerAuthToken instead.
    at Module.getClientAuthToken (/Users/jwatzman/monorepo/opensource/sdk-js/packages/server/dist/cjs/index.js:31:15)
```


Reviewers: flooey, jozef-mokry

Reviewed By: jozef-mokry

Pull Request: https://github.com/getcord/monorepo/pull/4760

monorepo-commit: 8daef375fc5116f257ec2140b53a9d882986ec50