Fix typechecking of our sdk packages
Right now `npm run tsc-packages` fails with an error:
```
error TS2688: Cannot find type definition file for '@types'.
  The file is in the program because:
    Entry point for implicit type library '@types'
```
[Example](https://github.com/getcord/monorepo/runs/6963637360?check_suite_focus=true)

I don't understand what the problem is, but @sven-of-cord found out that
if we run `npm ci` only for the packages first (ie before we run it in
monorepo/) then typechecking works again.

Test Plan:
run locally:
```
mv node_modules node_modules_foo # slow internet, I did not want to delete
cd opensource/cord-sdk
npm ci
npm run tsc-packages
```
This runs successfully and failed when I tried to use a React type in
our types/ package.

Also, the `build` action of this PR should run the new workflow

Reviewers: sven-of-cord, flooey

Reviewed By: sven-of-cord

Pull Request: https://github.com/getcord/monorepo/pull/1570

monorepo-commit: 783f9519f8a7eca15885a4b39307dd03346e5a49